# This is a basic workflow to help you get started with Actions

name: SyncDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

env:
  TARGET_REPO_INTERMEDIATE_BRANCH: 'intermediate'
  TARGET_REPO_BRANCH: 'develop'
  TARGET_REPO_URL: ${{ secrets.TARGET_REPO_URL }}
  TARGET_GITHUB_HOST: ${{ secrets.TARGET_GITHUB_HOST }}
  TARGET_REPO_REVIEWER: ${{ secrets.TARGET_REPO_REVIEWER }}
  TARGET_REPO_USER: ${{ secrets.TARGET_REPO_USER }}
  TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync-doces"
  sync-doces:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.1

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          COMMIT_ID: ${{ github.sha }}
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/syncDocForAction.sh
          $GITHUB_WORKSPACE/scripts/syncDocForAction.sh
